### ISSUE TITLE
Martinate has trouble finding DSSP

### ISSUE THREAD

**Issue by jbarnoud** [Tsjerk/gromit#1]
Martinate search for DSSP on the behalf of martinize. Yet, martinate looks for a program called `dssp` while the program often has an other name such as `mkdssp`. Also, it ignores the option `--martinize-dssp` that can be passed for martinize to find DSSP.

I see several ways of solving that issue:

* extend the range of names that martinate looks for
* let martinize take care of searching DSSP
* detect `--martinize-dssp`
* have a `-dssp` option

**Comment by jbarnoud** [comment]
Note that martinate actually have an undocumented `-dssp` option, but that option is not used.

**Comment by jbarnoud** [comment]
My bad: the `-dssp` option is used, but it does not behave in the same way as in martinize: while martinize is fine with the name of the dssp program, martinate wants a path.

**Comment by Tsjerk** [comment]
DSSP is now handled in the same way as martinize/insane/gmx... See further comment there.
