### ISSUE TITLE
[martinate] Error in semiisotropic pressure coupling during equilibration

### ISSUE THREAD

**Issue by jbarnoud** [Tsjerk/gromit#13]
Using martinate to setup a membrane simulation for gromacs 5.1.4, I get an error message during setp 4:

```
Command line:
  gmx grompp -f pr-npt-0.005.mdp -po pr-npt-0.005-out.mdp -c membrane-PR-NVT.gro -p membrane-cg.top -n me
mbrane-cg.ndx -o membrane-PR-NPT-0.005.tpr -maxwarn -1


ERROR 1 [file pr-npt-0.005.mdp, line 39]:
  Right hand side '10 10' for parameter 'tau_p' in parameter file is not a
  real value
```

It seems that, despite the use of gromacs 5, `tau_p` is given as a vector of 2 values instead of a single scalar. I think this happens because of [line 2254](https://github.com/Tsjerk/gromit/blob/master/martinate.sh#L2254).

The same problem seems to be fixed for the production around [line 2336](https://github.com/Tsjerk/gromit/blob/master/martinate.sh#L2336).

**Comment by jvuo** [comment]
Currently using gromacs 5.1.4, ran into the same error.

However simply changing line [2263](https://github.com/Tsjerk/gromit/blob/master/martinate.sh#L2263) to: 

`$MEMBRANE && __mdp_equil__tau_p=$__mdp_equil__tau_p`

and changing line [2350](https://github.com/Tsjerk/gromit/blob/master/martinate.sh#L2350) to:

`__mdp_mem__tau_p=12.0`

seems to take care of the issue.

Seems to be an issue that was tolerated in gromacs below 5.1.x but no longer above 5.1.x. [See also](http://thread.gmane.org/gmane.science.biology.gromacs.user/86180)
