### ISSUE TITLE
Martinate search martinize and insane in its directory

### ISSUE THREAD

**Issue by jbarnoud** [Tsjerk/gromit#2]
Martinate assumes that martinize and insane are in the same directory as it (`.../gromit/`). This is wrong as both martinize and insane have no reason to be there.

The culprit lines are [394](https://github.com/Tsjerk/gromit/blob/master/martinate.sh#L394) and [395](https://github.com/Tsjerk/gromit/blob/master/martinate.sh#L395).

**Comment by Tsjerk** [comment]
Yes, design flaw. Proposal:

1. Check ENV
2. Check self directory
3. Check PATH
4. Override with -insane/-martinize

I'm thinking whether a function for dependency checking/setting would be a good option.

**Comment by Tsjerk** [comment]
I added an array at the top for listing the dependency names, the expected executables and the possible environment variables. 

The executable can be specified (overridden) using the name as option (-dssp, -martinize, ...). A structure for checking arguments against the dependencies is added in the argument handling loop.

I added a function which tries to track the executable for a named dependency, following the rules as in the earlier comment. 

I added a FATAL statement/function and a dependency_not_found_error function.

I think we should have more of these error functions, and should make up our mind on naming schemes, but that will be a new issue.

Please check the changes and if they work (I tested briefly), and close this issue if this is cool.
