### ISSUE TITLE
Unexpected FF when -sol is not defined

### ISSUE THREAD

**Issue by jbarnoud** [Tsjerk/gromit#9]
Running martinate with `-ff martini22p` but not `-sol` leads to `martini22.py` being used instead of `martini22p.py`.

This is due to `$SID` not being set—as `$SOL` is not defined—resulting in `$FFMARTINIPY` begin set to `martini22.py` instead of `martini22p.py`.

`martini22p.py` should be used when `--ff martini22p` is passed to martinate, regardless of `-sol` begin passed or not.

**Comment by Tsjerk** [comment]
This should be covered by the block starting at line 566. Guess is that the comparison in line 568 is incorrect.

**Comment by jbarnoud** [comment]
After further investigations, it appeared that I was doing it wrong: `-ff` expects an atomistic force field rather than the coarse grained one. By setting `-cg` to `martini22p`, I get the expected behavior.
